In [1]:
import pandas as pd

In [6]:
df=pd.read_csv("Iris.csv",header=None)

In [3]:
print(df.head())

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [9]:
print(df.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
df.columns = ['SepalLengthCm',
              'SepalWidthCm',
              'PetalLengthCm',
              'PetalWidthCm',
              'Species']

In [12]:
print(df.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
print(df.shape)

(150, 5)

In [14]:
setosa_data = df[df['Species']=='Iris-setosa']

In [15]:
versicolor_data = df[df['Species']=='Iris-versicolor']

In [16]:
print(setosa_data.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [17]:
print(versicolor_data.head())

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor

In [18]:
df_concat = pd.concat([setosa_data,versicolor_data])

In [19]:
print(df_concat)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0             5.1           3.5            1.4           0.2      Iris-setosa
1             4.9           3.0            1.4           0.2      Iris-setosa
2             4.7           3.2            1.3           0.2      Iris-setosa
3             4.6           3.1            1.5           0.2      Iris-setosa
4             5.0           3.6            1.4           0.2      Iris-setosa
..            ...           ...            ...           ...              ...
95            5.7           3.0            4.2           1.2  Iris-versicolor
96            5.7           2.9            4.2           1.3  Iris-versicolor
97            6.2           2.9            4.3           1.3  Iris-versicolor
98            5.1           2.5            3.0           1.1  Iris-versicolor
99            5.7           2.8            4.1           1.3  Iris-versicolor

[100 rows x 5 columns]

In [20]:
df_concat.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
df_sorted = df.sort_values(by='PetalLengthCm',ascending=True)

In [22]:
df_sorted.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
22            4.6           3.6            1.0           0.2  Iris-setosa
13            4.3           3.0            1.1           0.1  Iris-setosa
14            5.8           4.0            1.2           0.2  Iris-setosa
35            5.0           3.2            1.2           0.2  Iris-setosa
16            5.4           3.9            1.3           0.4  Iris-setosa

In [23]:
df_tran = df.head().T

In [24]:
print(df_tran)

                         0            1            2            3            4
SepalLengthCm          5.1          4.9          4.7          4.6          5.0
SepalWidthCm           3.5          3.0          3.2          3.1          3.6
PetalLengthCm          1.4          1.4          1.3          1.5          1.4
PetalWidthCm           0.2          0.2          0.2          0.2          0.2
Species        Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

In [25]:
melted_data = pd.melt(df,
                      id_vars=['Species'],
                      value_vars=['SepalLengthCm',
                                  'SepalWidthCm',
                                  'PetalLengthCm',
                                  'PetalWidthCm'],
                      var_name='measurement',
                      value_name='value')

In [26]:
print(melted_data.head())

       Species    measurement  value
0  Iris-setosa  SepalLengthCm    5.1
1  Iris-setosa  SepalLengthCm    4.9
2  Iris-setosa  SepalLengthCm    4.7
3  Iris-setosa  SepalLengthCm    4.6
4  Iris-setosa  SepalLengthCm    5.0

In [27]:
wide = melted_data.pivot_table(index='Species',
                               columns='measurement',
                               values='value',
                               aggfunc='mean')

In [28]:
print(wide.head())

measurement      PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm
Species
Iris-setosa              1.464         0.244          5.006         3.418
Iris-versicolor          4.260         1.326          5.936         2.770
Iris-virginica           5.552         2.026          6.588         2.974