In [1]:
import pandas as pd

df = pd.read_csv("movies_metadata.csv",low_memory=False)

In [3]:
print(df.head())

   adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en
1                                   NaN   8844  tt0113497                en
2                                   NaN  15602  tt0113228                en
3                                   NaN  31357  tt0114885                en
4                                   NaN  11862  tt0113041                en

                original_title  \
0                    Toy Story
1                      Jumanji
2             Grumpier Old Men
3            Waiting to Exhale
4  Father of the Bride Part II

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15
2  A family wedding reignites the ancient feud be...  ...   1995-12-22
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4  Just when George Banks has recovered from his ...  ...   1995-02-10

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released                                                NaN
1  Released          Roll the dice and unleash the excitement!
2  Released  Still Yelling. Still Fighting. Still Ready for...
3  Released  Friends are the people who let you be yourself...
4  Released  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count
0                    Toy Story  False          7.7     5415.0
1                      Jumanji  False          6.9     2413.0
2             Grumpier Old Men  False          6.5       92.0
3            Waiting to Exhale  False          6.1       34.0
4  Father of the Bride Part II  False          5.7      173.0

[5 rows x 24 columns]

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  str
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(1), str(19)
memory usage: 8.3+ MB
None

In [5]:
df = df[['original_language',
         'vote_average',
         'vote_count',
         'popularity']]

In [6]:
print(df.isnull().sum())

original_language    11
vote_average          6
vote_count            6
popularity            5
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df['vote_average'] = pd.to_numeric(df['vote_average'],errors='coerce')
df['vote_count'] = pd.to_numeric(df['vote_count'],errors='coerce')
df['popularity'] = pd.to_numeric(df['popularity'],errors='coerce')

In [9]:
df = df.dropna()

In [10]:
english_data = df[df['original_language']=='en']

french_data = df[df['original_language']=='fr']

In [11]:
print(english_data.head())

  original_language  vote_average  vote_count  popularity
0                en           7.7      5415.0   21.946943
1                en           6.9      2413.0   17.015539
2                en           6.5        92.0   11.712900
3                en           6.1        34.0    3.859495
4                en           5.7       173.0    8.387519

In [12]:
print(french_data.head())

   original_language  vote_average  vote_count  popularity
28                fr           7.6       308.0    9.822423
32                fr           6.8         4.0    0.745542
58                fr           6.5         2.0    0.120789
67                fr           6.0        43.0    2.518051
72                fr           6.6         8.0    1.479446

In [13]:
df_concat = pd.concat([english_data,french_data])

In [14]:
print(df_concat)

      original_language  vote_average  vote_count  popularity
0                    en           7.7      5415.0   21.946943
1                    en           6.9      2413.0   17.015539
2                    en           6.5        92.0   11.712900
3                    en           6.1        34.0    3.859495
4                    en           5.7       173.0    8.387519
...                 ...           ...         ...         ...
45444                fr           6.1         8.0    0.208349
45447                fr           6.0         6.0    0.213973
45448                fr           5.0         2.0    0.071782
45450                fr           6.5        22.0    1.109068
45451                fr           6.5         6.0    0.225432

[34705 rows x 4 columns]

In [16]:
df_concat.head()

  original_language  vote_average  vote_count  popularity
0                en           7.7      5415.0   21.946943
1                en           6.9      2413.0   17.015539
2                en           6.5        92.0   11.712900
3                en           6.1        34.0    3.859495
4                en           5.7       173.0    8.387519

In [17]:
df_sorted = df.sort_values(by='vote_average',ascending=True)

In [18]:
df_sorted.head()

      original_language  vote_average  vote_count  popularity
36819                fi           0.0         0.0    1.147538
23100                en           0.0         0.0    0.037500
23097                en           0.0         0.0    0.072810
23140                en           0.0         0.0    0.008309
2143                 en           0.0         0.0    0.304363

In [19]:
df_tran = df.head().T

In [20]:
print(df_tran)

                           0          1        2         3         4
original_language         en         en       en        en        en
vote_average             7.7        6.9      6.5       6.1       5.7
vote_count            5415.0     2413.0     92.0      34.0     173.0
popularity         21.946943  17.015539  11.7129  3.859495  8.387519

In [21]:
melted_data = pd.melt(df,
                      id_vars=['original_language'],
                      value_vars=['vote_average',
                                  'vote_count',
                                  'popularity'],
                      var_name='measurement',
                      value_name='value')

In [22]:
print(melted_data.head())

  original_language   measurement  value
0                en  vote_average    7.7
1                en  vote_average    6.9
2                en  vote_average    6.5
3                en  vote_average    6.1
4                en  vote_average    5.7

In [23]:
wide = melted_data.pivot_table(index='original_language',
                               columns='measurement',
                               values='value',
                               aggfunc='mean')

In [24]:
print(wide.head())

measurement        popularity  vote_average  vote_count
original_language
ab                   1.182567      5.000000   13.200000
af                   3.291494      6.200000   51.000000
am                   0.332316      7.450000    3.500000
ar                   1.002735      6.817949   15.384615
ay                   0.640637      6.000000    2.000000