In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("adult.csv",low_memory=False)

In [4]:
print(df.head())

print(df.info())

   39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse
1  38            Private  215646     HS-grad    9             Divorced
2  53            Private  234721        11th    7   Married-civ-spouse
3  28            Private  338409   Bachelors   13   Married-civ-spouse
4  37            Private  284582     Masters   14   Married-civ-spouse

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40
2   Handlers-cleaners         Husband   Black     Male      0   0   40
3      Prof-specialty            Wife   Black   Female      0   0   40
4     Exec-managerial            Wife   White   Female      0   0   40

    United-States   <=50K
0   United-States   <=50K
1   United-States   <=50K
2   United-States   <=50K
3            Cuba   <=50K
4   United-States   <=50K
<class 'pandas.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   39              32560 non-null  int64
 1    State-gov      32560 non-null  str
 2    77516          32560 non-null  int64
 3    Bachelors      32560 non-null  str
 4    13             32560 non-null  int64
 5    Never-married  32560 non-null  str
 6    Adm-clerical   32560 non-null  str
 7    Not-in-family  32560 non-null  str
 8    White          32560 non-null  str
 9    Male           32560 non-null  str
 10   2174           32560 non-null  int64
 11   0              32560 non-null  int64
 12   40             32560 non-null  int64
 13   United-States  32560 non-null  str
 14   <=50K          32560 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB
None

In [5]:
df.columns = ['age',
              'workclass',
              'fnlwgt',
              'education',
              'education_num',
              'marital_status',
              'occupation',
              'relationship',
              'race',
              'sex',
              'capital_gain',
              'capital_loss',
              'hours_per_week',
              'native_country',
              'income']

In [6]:
df = df.dropna()

In [7]:
india_data = df[df['native_country']=='India']

us_data = df[df['native_country']=='United-States']

In [8]:
print(india_data.head())

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education_num, marital_status, occupation, relationship, race, sex, capital_gain, capital_loss, hours_per_week, native_country, income]
Index: []

In [9]:
print(us_data.head())

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education_num, marital_status, occupation, relationship, race, sex, capital_gain, capital_loss, hours_per_week, native_country, income]
Index: []

In [10]:
df = df[['native_country',
         'sex',
         'race',
         'age',
         'hours_per_week',
         'education_num']]

In [11]:
df = df.dropna()

In [15]:
india_data = df[df['native_country']==' India']
us_data = df[df['native_country']==' United-States']

In [16]:
print(india_data.head())

     native_country      sex                 race  age  hours_per_week  \
10            India     Male   Asian-Pac-Islander   30              40
891           India   Female   Asian-Pac-Islander   28              40
967           India     Male   Asian-Pac-Islander   48              40
1028          India     Male   Asian-Pac-Islander   48              50
1094          India     Male   Asian-Pac-Islander   22              20

      education_num
10               13
891              11
967              13
1028             14
1094             13

In [17]:
print(us_data.head())

   native_country      sex    race  age  hours_per_week  education_num
0   United-States     Male   White   50              13             13
1   United-States     Male   White   38              40              9
2   United-States     Male   Black   53              40              7
4   United-States   Female   White   37              40             14
6   United-States     Male   White   52              45              9

In [18]:
df_concat = pd.concat([india_data,us_data])

In [19]:
print(df_concat)

       native_country      sex                 race  age  hours_per_week  \
10              India     Male   Asian-Pac-Islander   30              40
891             India   Female   Asian-Pac-Islander   28              40
967             India     Male   Asian-Pac-Islander   48              40
1028            India     Male   Asian-Pac-Islander   48              50
1094            India     Male   Asian-Pac-Islander   22              20
...               ...      ...                  ...  ...             ...
32555   United-States   Female                White   27              38
32556   United-States     Male                White   40              40
32557   United-States   Female                White   58              40
32558   United-States     Male                White   22              20
32559   United-States   Female                White   52              40

       education_num
10                13
891               11
967               13
1028              14
1094              13
...              ...
32555             12
32556              9
32557              9
32558              9
32559              9

[29269 rows x 6 columns]

In [20]:
df.head()

   native_country      sex    race  age  hours_per_week  education_num
0   United-States     Male   White   50              13             13
1   United-States     Male   White   38              40              9
2   United-States     Male   Black   53              40              7
3            Cuba   Female   Black   28              40             13
4   United-States   Female   White   37              40             14

In [21]:
df_sorted = df.sort_values(by='hours_per_week',ascending=True)

In [24]:
df_sorted.head(20)

,native_country,sex,race,age,hours_per_week,education_num
32524,?,Female,White,81,1,11
20071,United-States,Male,White,65,1,9
11450,United-States,Male,White,27,1,9
24283,United-States,Male,White,57,1,9
5631,United-States,Female,White,45,1,14
29751,United-States,Female,White,69,1,12
5807,United-States,Male,White,76,1,6
5765,United-States,Female,White,62,1,10
19749,Vietnam,Male,Asian-Pac-Islander,23,1,9
19336,United-States,Male,Asian-Pac-Islander,72,1,9
8446,United-States,Female,White,67,1,11
25077,United-States,Female,White,74,1,6
23535,United-States,Male,White,69,1,10
9146,China,Female,Asian-Pac-Islander,75,1,6
5589,United-States,Female,White,78,1,9
1035,?,Male,White,66,1,5
1261,United-States,Female,White,69,1,11
22959,United-States,Male,Black,21,1,9
188,United-States,Male,White,58,1,16
20908,United-States,Female,White,77,1,10

In [25]:
df_tran = df.head().T

In [26]:
print(df_tran)

                             0               1               2        3  \
native_country   United-States   United-States   United-States     Cuba
sex                       Male            Male            Male   Female
race                     White           White           Black    Black
age                         50              38              53       28
hours_per_week              13              40              40       40
education_num               13               9               7       13

                             4
native_country   United-States
sex                     Female
race                     White
age                         37
hours_per_week              40
education_num               14

In [27]:
df_tran.head()

,0,1,2,3,4
native_country,United-States,United-States,United-States,Cuba,United-States
sex,Male,Male,Male,Female,Female
race,White,White,Black,Black,White
age,50,38,53,28,37
hours_per_week,13,40,40,40,40

In [28]:
melted_data = pd.melt(df,
                      id_vars=['native_country'],
                      value_vars=['age',
                                  'hours_per_week',
                                  'education_num'],
                      var_name='measurement',
                      value_name='value')

In [29]:
print(melted_data.head())

   native_country measurement  value
0   United-States         age     50
1   United-States         age     38
2   United-States         age     53
3            Cuba         age     28
4   United-States         age     37

In [30]:
wide = melted_data.pivot_table(index='native_country',
                               columns='measurement',
                               values='value',
                               aggfunc='mean')

In [31]:
wide.head()

measurement           age  education_num  hours_per_week
native_country
?               38.725557      10.598628       41.512864
Cambodia        37.789474       8.789474       40.894737
Canada          42.545455      10.652893       40.404959
China           42.533333      11.120000       37.786667
Columbia        39.711864       9.372881       39.067797